--DATABASE LEVEL 1
CREATE TABLE AGRICULTOR(
    IDAGRICULTOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M', 'F') NOT NULL,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

INSERT INTO AGRICULTOR(NOME, SEXO, EMAIL, CPF) VALUES('NICOLAS CASTANHA MENDONÇA','M','NICOLINHAS77@GMAIL.COM','129.782.923-18');
INSERT INTO AGRICULTOR(NOME, SEXO, EMAIL, CPF) VALUES('LETICIA COUTINHO DA SILVA','F','LETICIA_AGRO@GMAIL.COM','192.432.983-13');
INSERT INTO AGRICULTOR(NOME, SEXO, EMAIL, CPF) VALUES('LUCAS MERCADOR PORTUGUAL','M','LUCASAGROPYTHON@GMAIL.COM','482.378.219-01');
INSERT INTO AGRICULTOR(NOME, SEXO, EMAIL, CPF) VALUES('FRANSCISCO DA CUNHA','M','FRANSCISCOCUNHA128@GMAIL.COM','529.167.123-12');
INSERT INTO AGRICULTOR(NOME, SEXO, EMAIL, CPF) VALUES('SANDRO BASTOS DE SANTOS','M','SANDRINHO17823@GMAIL.COM','282.782.982-89');
INSERT INTO AGRICULTOR(NOME, SEXO, EMAIL, CPF) VALUES('SOLANGE FREITAS DA COSTA','F','SOLFREITAS@HOTMAIL.COM','182.902.182-09');
INSERT INTO AGRICULTOR(NOME, SEXO, EMAIL, CPF) VALUES('GIULIANA DAHORA','F','GIUGIUSIMS123@GMAIL.COM','192.402.458-02')

CREATE TABLE END_TERRAS(
	IDTERRAS INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_AGRICULTOR INT NOT NULL,
	FOREIGN KEY (ID_AGRICULTOR) REFERENCES AGRICULTOR(IDAGRICULTOR)
);

INSERT INTO END_TERRAS(RUA, BAIRRO, CIDADE, ESTADO, ID_AGRICULTOR) VALUES('ALMEIDA DE FREITAS','AFONSO', 'CACHOEIRINHA', 'PR', '1');
INSERT INTO END_TERRAS(RUA, BAIRRO, CIDADE, ESTADO, ID_AGRICULTOR) VALUES('BOA VISTA','SANTANA', 'SÃO GONÇALO', 'RJ', '2');
INSERT INTO END_TERRAS(RUA, BAIRRO, CIDADE, ESTADO, ID_AGRICULTOR) VALUES('SÃO CAETANO','IBIRAPUERA', 'ALASCA', 'RO', '3');
INSERT INTO END_TERRAS(RUA, BAIRRO, CIDADE, ESTADO, ID_AGRICULTOR) VALUES('ESPANHA','BUENOS AIRES', 'MENDONZA', 'SP', '4');
INSERT INTO END_TERRAS(RUA, BAIRRO, CIDADE, ESTADO, ID_AGRICULTOR) VALUES('PONTE VELHA','PARQUE DAS ÁRVORES', 'PRAIA GRANDE', 'SP', '5');
INSERT INTO END_TERRAS(RUA, BAIRRO, CIDADE, ESTADO, ID_AGRICULTOR) VALUES('LUCAS N.','ZONA NOROESTE', 'SANTOS ', 'SP', '6');
INSERT INTO END_TERRAS(RUA, BAIRRO, CIDADE, ESTADO, ID_AGRICULTOR) VALUES('BOA VISTA','SANTANA', 'SÃO GONÇALO', 'AM', '7');

CREATE TABLE PLANTACAO(
	IDPLANTACAO INT PRIMARY KEY AUTO_INCREMENT,
	TIPO VARCHAR(30) NOT NULL,
	LUCRO_MENSAL DOUBLE NOT NULL,
	LUCRO_ANUAL DOUBLE NOT NULL,
	INFLUENCIA VARCHAR(30) NOT NULL,
	ID_AGRICULTOR INT NOT NULL,
	ID_TERRAS INT NOT NULL,
	FOREIGN KEY(ID_AGRICULTOR) REFERENCES AGRICULTOR(IDAGRICULTOR),
	FOREIGN KEY(ID_TERRAS) REFERENCES END_TERRAS(IDTERRAS)
);

INSERT INTO PLANTACAO(TIPO, LUCRO_MENSAL, LUCRO_ANUAL, INFLUENCIA, ID_AGRICULTOR, ID_TERRAS) VALUES('CENOURA', '3532.75', '42393.53', 'INSETICIDAS', '1', '1');
INSERT INTO PLANTACAO(TIPO, LUCRO_MENSAL, LUCRO_ANUAL, INFLUENCIA, ID_AGRICULTOR, ID_TERRAS) VALUES('TOMATE', '5234.32', '62811.84', 'RATICIDAS', '2', '2');
INSERT INTO PLANTACAO(TIPO, LUCRO_MENSAL, LUCRO_ANUAL, INFLUENCIA, ID_AGRICULTOR, ID_TERRAS) VALUES('ARROZ', '8800.21', '105602.52', 'ACARICIDAS', '3', '3');
INSERT INTO PLANTACAO(TIPO, LUCRO_MENSAL, LUCRO_ANUAL, INFLUENCIA, ID_AGRICULTOR, ID_TERRAS) VALUES('BATATA', '3654.76', '43857.12', 'HERBICIDAS', '4', '4');
INSERT INTO PLANTACAO(TIPO, LUCRO_MENSAL, LUCRO_ANUAL, INFLUENCIA, ID_AGRICULTOR, ID_TERRAS) VALUES('ARROZ', '4832.48', '57989.76', 'INSETICIDAS', '5', '5');
INSERT INTO PLANTACAO(TIPO, LUCRO_MENSAL, LUCRO_ANUAL, INFLUENCIA, ID_AGRICULTOR, ID_TERRAS) VALUES('AGRIÃO', '10987.65', '659.259', 'INSETICIDAS', '6', '6');
INSERT INTO PLANTACAO(TIPO, LUCRO_MENSAL, LUCRO_ANUAL, INFLUENCIA, ID_AGRICULTOR, ID_TERRAS) VALUES('MANJERICÃO', '3753.12', '4503.744', 'FUNGICIDAS', '7', '7');

--DATABAS LEVEL 2
CREATE TABLE EMPRESAS(
    IDEMPRESAS INT PRIMARY KEY AUTO_INCREMENT,
    CNPJ VARCHAR(30) NOT NULL,
    SETOR VARCHAR(30) NOT NULL,
    PROD_INFLUENCIA VARCHAR(30) NOT NULL,
    ID_CLIENTE INT NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES AGRICULTOR(IDAGRICULTOR)
);

INSERT INTO EMPRESAS(CNPJ, SETOR, PROD_INFLUENCIA, ID_CLIENTE) VALUES('95.670.415/0001-89','CENOURA','INSETICIDAS','1');
INSERT INTO EMPRESAS(CNPJ, SETOR, PROD_INFLUENCIA, ID_CLIENTE) VALUES('62.550.926/0001-08','TOMATE','RATICIDAS','2');
INSERT INTO EMPRESAS(CNPJ, SETOR, PROD_INFLUENCIA, ID_CLIENTE) VALUES('14.061.866/0001-17','ARROZ','ACARICIDAS','3');
INSERT INTO EMPRESAS(CNPJ, SETOR, PROD_INFLUENCIA, ID_CLIENTE) VALUES('54.164.824/0001-26','BATATA','HERBICIDAS','4');
INSERT INTO EMPRESAS(CNPJ, SETOR, PROD_INFLUENCIA, ID_CLIENTE) VALUES('79.807.697/0001-67','ARROZ', 'INSETICIDAS','5');
INSERT INTO EMPRESAS(CNPJ, SETOR, PROD_INFLUENCIA, ID_CLIENTE) VALUES('41.867.626/0001-87','AGRIÃO','INSETICIDAS','6');
INSERT INTO EMPRESAS(CNPJ, SETOR, PROD_INFLUENCIA, ID_CLIENTE) VALUES('46.345.176/0001-86','MANJERICÃO','FUNGICIDAS','7');

--DATABASE LEVEL 3
CREATE TABLE PROCESSOS(
    IDPROCESSOS INT PRIMARY KEY AUTO_INCREMENT,
    NUM_PROCESSO VARCHAR(30) NOT NULL,
    CNPJ_EMPRESA VARCHAR(30) NOT NULL,
    ID_EMPRESA INT NOT NULL,
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS(IDEMPRESAS)
);

INSERT INTO PROCESSOS(NUM_PROCESSO, CNPJ_EMPRESA, ID_EMPRESA) VALUES('5332633-90.2022.2.00.7621','95.670.415/0001-89','1');
INSERT INTO PROCESSOS(NUM_PROCESSO, CNPJ_EMPRESA, ID_EMPRESA) VALUES('5644373-33.2022.8.25.3172','62.550.926/0001-08','2');
INSERT INTO PROCESSOS(NUM_PROCESSO, CNPJ_EMPRESA, ID_EMPRESA) VALUES('17472803-11.2022.3.00.2734','14.061.866/0001-17','3');
INSERT INTO PROCESSOS(NUM_PROCESSO, CNPJ_EMPRESA, ID_EMPRESA) VALUES('2665345-95.2022.9.21.7992','54.164.824/0001-26','4');
INSERT INTO PROCESSOS(NUM_PROCESSO, CNPJ_EMPRESA, ID_EMPRESA) VALUES('7872338-58.2022.4.01.5697','79.807.697/0001-67','5');
INSERT INTO PROCESSOS(NUM_PROCESSO, CNPJ_EMPRESA, ID_EMPRESA) VALUES('3778270-19.2022.6.26.4600','41.867.626/0001-87','6');
INSERT INTO PROCESSOS(NUM_PROCESSO, CNPJ_EMPRESA, ID_EMPRESA) VALUES('8205975-62.2022.7.10.2968','46.345.176/0001-86','7');